### ISSUE TITLE
Any way to report CLIMATE_ACTION ? 

### ISSUE THREAD

**Issue by bearpawmaxim** [paveldn/haier-esphome#11]
Hi! Is there any way to report the current action of the climate? I mean I'm interested in getting to know whether it is idle now or heating/cooling? (compressor and electric_heating flags in protocol?)
Thanks!

**Comment by paveldn** [comment]
Hi @bearpawmaxim, I thought about this and I don't think there is a way to do it. For hOn, we have a protocol but the only parameter I can use for this is an electricHeatingStatus (which is on or off) so if it is ON it is probably doing heating. But nothing for the cooling. So I am afraid there is no explicit way. Potentially there are such things as compressorStatus, expansionValveOpenDegree, fourWayValveStatus, etc. But I have no idea what it is and how can I use them to detect the state, beside that in my case, it is always 0. So probably they just placeholders for future models.

**Comment by bearpawmaxim** [comment]
Okay, thanks!
