### ISSUE TITLE
Use Friendly Name instead of device_name substitution

### ISSUE THREAD

**Issue by Marko298** [paveldn/haier-esphome#17]
Hello, according to ESPhome docs you can use friendly_name to prefix all names with device name instead of device_name substitution. If you are OK with that I can provide PR to update that

**Comment by paveldn** [comment]
Hi @Marko298 ,
Never tried this friendly_name before. Will it also work with the ESPhome web server? 
Sure, if it is possible to make the config simpler why not? Pleas make PR. Thanks.

**Comment by Marko298** [comment]
#18 here you go
