### ISSUE TITLE
Question can i also cut and replace the default ESP32-for-Haier with an esp board

### ISSUE THREAD

**Issue by DBuit** [paveldn/haier-esphome#20]
Hello,

Just quick question i have a ESP32-for-haier board on my AC.
I prefer not to touch this board and just cut the cable and solder a wemos to it, should that also work or can this only work by flashing the orginal board?

Thank you

**Comment by paveldn** [comment]
@DBuit 
Yes, you can. The component will work with any ESP8266 or ESP32 and even Rpi pico.
