### ISSUE TITLE
Disabling led on esp module

### ISSUE THREAD

**Issue by Tymon3310** [paveldn/haier-esphome#42]
Is there any way to disable the led indicator on nodemcuv3, that controls my ac, this led blinks every time that it communicates with HA, witch is very distracting(ac has very thin cover so its shining thru)

**Comment by paveldn** [comment]
Hello @Tymon3310,
Not sure about your boar specifically but I think it is blinking not during HA transmission but during communication between the ESP board and AC. Most likely LED is connected to some GPIO that you used as a UART port. You can try to use another GPIO for software UART (but of course you will need to change your wiring and ESPHome config). But I would suggest just putting a piece of black tape on top of the LED to block the light. It will be as effective and much easier to do 😄
