### ISSUE TITLE
Where can i find   local_haier file ?

### ISSUE THREAD

**Issue by lakusz1github** [paveldn/haier-esphome#45]
Hi

In yaml file is line:
```
packages:
  local_haier: !include configs/external_components/local_haier.yaml
```

but i cant find this file in github. Sorry for dump question ;)

I want take wemos_d1_mini.yaml, change one line for smartair2, and copy "config" folder to my ESPHome.

**Comment by paveldn** [comment]
Hi.

It is here: https://github.com/paveldn/haier-esphome/blob/master/configs/external_components/local_haier.yaml
But actually, you don't need this package unless you want to use some experimental things. If you want to use code that is already included in ESPHome just remove this package reference.
