### ISSUE TITLE
ESP 2024.10.0 update - The beeper option is deprecated, use beeper_on/beeper_off actions or beeper switch for a haier platform instead. 

### ISSUE THREAD

**Issue by andremain** [paveldn/haier-esphome#60]
As of the last ESP update i cannot update the firmware of my device stating:
The beeper option is deprecated, use beeper_on/beeper_off actions or beeper switch for a haier platform instead.

"INFO ESPHome 2024.10.0
INFO Reading configuration /config/esphome/bedroom-3-ac-esp32.yaml...
Failed config

climate.haier: [source /config/esphome/bedroom-3-ac-esp32.yaml:49]
  platform: haier
  id: haier_ac
  protocol: hOn
  name: Haier AC
  uart_id: ac_port
  wifi_signal: True
  
  The beeper option is deprecated, use beeper_on/beeper_off actions or beeper switch for a haier platform instead.
  beeper: True
  display: True
  visual: 
    min_temperature: 16 °C
    max_temperature: 30 °C
    temperature_step: 1 °C"

What do i need to do to fix it?

This is my original code:

"esphome:
  name: bedroom-3-ac-esp32
  friendly_name: Bedroom 3 AC ESP32

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "1234"

ota:
  platform: esphome
  password: "1234"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bedroom-3-Ac-Esp32"
    password: "1234"

captive_portal:

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

uart:
  baud_rate: 9600
  tx_pin: 17
  rx_pin: 16
  id: ac_port  

climate:
  - platform: haier
    id: haier_ac
    protocol: hOn
    name: Haier AC 
    uart_id: ac_port
    wifi_signal: true           # Optional, default true, enables WiFI signal transmission from ESP to AC
    beeper: true                # Optional, default true, disables beep on commands from ESP
    display: true               # Optional, default true, can be used to turn off LED display
    #answer_timeout:: 200ms      # Optional, request answer timeout, can be used to increase the timeout
                                # for some ACs that have longer answer delays
    #outdoor_temperature:        # Optional, outdoor temperature sensor
    #name: Haier AC outdoor temperature
    visual:                     # Optional, you can use it to limit min and max temperatures in UI (not working for remote!)
      min_temperature: 16 °C
      max_temperature: 30 °C
      temperature_step: 1 °C
    supported_modes:            # Optional, can be used to disable some modes if you don't need them
      - 'OFF'
      - COOL
      - HEAT
      - DRY
      - FAN_ONLY
    supported_presets:          # Optional, can be used to disable some presets if your AC does not support it
      - AWAY
      - BOOST
      - SLEEP
    supported_swing_modes:      # Optional, can be used to disable some (or all) swing modes if your AC does not support it
      - 'OFF'
      - VERTICAL
      - HORIZONTAL
      - BOTH
    on_alarm_start:
      then:
        - logger.log:
            level: WARN
            format: "Alarm activated. Code: %d. Message: \"%s\""
            args: [ code, message]
    on_alarm_end:
      then:
        - logger.log:
            level: INFO
            format: "Alarm deactivated. Code: %d. Message: \"%s\""
            args: [ code, message]

switch:
  - platform: template
    id: haier_display_switch
    name: Haier Display Switch
    restore_mode: RESTORE_DEFAULT_OFF
    icon: mdi:blur-radial
    lambda: |-
      return id(haier_ac).get_display_state();
    turn_on_action:
      climate.haier.display_on: haier_ac
    turn_off_action:
      climate.haier.display_off: haier_ac

  - platform: template
    id: haier_beeper_switch
    name: Haier Beeper Switch
    restore_mode: RESTORE_DEFAULT_OFF
    icon: mdi:volume-high
    lambda: |-
      return id(haier_ac).get_beeper_state();
    turn_on_action:
      climate.haier.beeper_on: haier_ac
    turn_off_action:
      climate.haier.beeper_off: haier_ac"

**Comment by paveldn** [comment]
@andremain 

Sorry braking changes. The error message says exactly what should be done:
remove the beeper option from climate and use the beeper switch for Haier integration. 
You can see an example here (maximum configuration):
https://github.com/paveldn/haier-esphome/blob/master/docs/hon_example.rst

**Comment by andremain** [comment]
IT worked.

Thanks a lot!

**Comment by paveldn** [comment]
You are welcome.
